### ISSUE TITLE
Providing slots

### ISSUE THREAD

**Issue by hmnd** [bryanmylee/svelte-render#1]
There doesn't currently seem to be a way to provide slots to the component in `createRender`. That would be a handy feature for a component such as a button where the text is naturally provided as a slot.

**Comment by bryanmylee** [comment]
We can probably use `<svelte:self>` to recursively render children defined as other render configurations.

I agree that it would be helpful for components like buttons that define text as the provided slot. I'm just worried that we'll end up defining an entirely new meta templating language within Svelte.

I'll work on a release.

**Comment by bryanmylee** [comment]
@hmnd I've released v1.6.0 which should provide this behavior with `.slot()`. Do check it out!
